def get_texts(language):
    return {
        'en': {
            'greeting': "Hello! Welcome to the bot.",
            'no_meetings': "No meetings.",
            'meetings_today': "Meetings for today:\n",
            'meetings_tomorrow': "Meetings for tomorrow:\n",
            'meetings_next_week': "Meetings for next week:\n",
            'meetings_this_week': "Meetings for this week:\n",
            'days_of_week': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
            'language_set': "Language has been set to English.",
            'choose_language': "Please choose your language:",
            'settings_command': "Change language settings",
            'time_thailand': "Time in Thailand",
            'time_ukraine': "Time in Ukraine",
            'goal': "Goal",
            'attendants': "Attendants",
            'location': "Location",
            'meet_link': "Meet Link",
            'restart_notice': "Please restart the app to update the menu.",
            'available_commands': "Here are the available commands:",
            'menu_notice': "You can also find these commands in the menu.",
            'command_descriptions': [
                ("start", "Start interacting with the bot"),
                ("today", "Get today's meetings"),
                ("tomorrow", "Get tomorrow's meetings"),
                ("today_tomorrow", "Get today's and tomorrow's meetings"),
                ("week", "Get this week's meetings"),
                ("next_week", "Get next week's meetings"),
                ("settings", "Change language settings")
            ]
        },
        'ru': {
            'greeting': "Здравствуйте! Добро пожаловать в бота.",
            'no_meetings': "Нет встреч.",
            'meetings_today': "Встречи на сегодня:\n",
            'meetings_tomorrow': "Встречи на завтра:\n",
            'meetings_next_week': "Встречи на следующую неделю:\n",
            'meetings_this_week': "Встречи на эту неделю:\n",
            'days_of_week': ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
            'language_set': "Язык установлен на Русский.",
            'choose_language': "Пожалуйста, выберите ваш язык:",
            'settings_command': "Изменить настройки языка",
            'time_thailand': "Время в Таиланде",
            'time_ukraine': "Время в Украине",
            'goal': "Цель",
            'attendants': "Участники",
            'location': "Место",
            'meet_link': "Ссылка на встречу",
            'restart_notice': "Пожалуйста, перезапустите приложение, чтобы обновить меню.",
            'available_commands': "Вот доступные команды:",
            'menu_notice': "Вы также можете найти эти команды в меню.",
            'command_descriptions': [
                ("start", "Начать взаимодействие с ботом"),
                ("today", "Получить встречи на сегодня"),
                ("tomorrow", "Получить встречи на завтра"),
                ("today_tomorrow", "Получить встречи на сегодня и завтра"),
                ("week", "Получить встречи на эту неделю"),
                ("next_week", "Получить встречи на следующую неделю"),
                ("settings", "Изменить настройки языка")
            ]
        },
        'uk': {
            'greeting': "Привіт! Ласкаво просимо до бота.",
            'no_meetings': "Немає зустрічей.",
            'meetings_today': "Зустрічі на сьогодні:\n",
            'meetings_tomorrow': "Зустрічі на завтра:\n",
            'meetings_next_week': "Зустрічі на наступний тиждень:\n",
            'meetings_this_week': "Зустрічі на цей тиждень:\n",
            'days_of_week': ['Понеділок', 'Вівторок', 'Середа', 'Четвер', 'П’ятниця', 'Субота', 'Неділя'],
            'language_set': "Мова встановлена на Українську.",
            'choose_language': "Будь ласка, оберіть вашу мову:",
            'settings_command': "Змінити налаштування мови",
            'time_thailand': "Час у Таїланді",
            'time_ukraine': "Час в Україні",
            'goal': "Мета",
            'attendants': "Учасники",
            'location': "Місце",
            'meet_link': "Посилання на зустріч",
            'restart_notice': "Будь ласка, перезапустіть додаток, щоб оновити меню.",
            'available_commands': "Ось доступні команди:",
            'menu_notice': "Ви також можете знайти ці команди в меню.",
            'command_descriptions': [
                ("start", "Почати взаємодію з ботом"),
                ("today", "Отримати зустрічі на сьогодні"),
                ("tomorrow", "Отримати зустрічі на завтра"),
                ("today_tomorrow", "Отримати зустрічі на сьогодні та завтра"),
                ("week", "Отримати зустрічі на цей тиждень"),
                ("next_week", "Отримати зустрічі на наступний тиждень"),
                ("settings", "Змінити налаштування мови")
            ]
        },
        'th': {
            'greeting': "สวัสดี! ยินดีต้อนรับสู่บอท.",
            'no_meetings': "ไม่มีการประชุม.",
            'meetings_today': "การประชุมสำหรับวันนี้:\n",
            'meetings_tomorrow': "การประชุมสำหรับพรุ่งนี้:\n",
            'meetings_next_week': "การประชุมสำหรับสัปดาห์หน้า:\n",
            'meetings_this_week': "การประชุมสำหรับสัปดาห์นี้:\n",
            'days_of_week': ['วันจันทร์', 'วันอังคาร', 'วันพุธ', 'วันพฤหัสบดี', 'วันศุกร์', 'วันเสาร์', 'วันอาทิตย์'],
            'language_set': "ตั้งค่าภาษาเป็นภาษาไทยแล้ว.",
            'choose_language': "กรุณาเลือกภาษาของคุณ:",
            'settings_command': "เปลี่ยนการตั้งค่าภาษา",
            'time_thailand': "เวลาในประเทศไทย",
            'time_ukraine': "เวลาในยูเครน",
            'goal': "เป้าหมาย",
            'attendants': "ผู้เข้าร่วม",
            'location': "สถานที่",
            'meet_link': "ลิงก์การประชุม",
            'restart_notice': "กรุณารีสตาร์ทแอปเพื่ออัปเดตเมนู.",
            'available_commands': "นี่คือคำสั่งที่ใช้ได้:",
            'menu_notice': "คุณยังสามารถค้นหาคำสั่งเหล่านี้ในเมนู.",
            'command_descriptions': [
                ("start", "เริ่มต้นการโต้ตอบกับบอท"),
                ("today", "รับการประชุมของวันนี้"),
                ("tomorrow", "รับการประชุมของพรุ่งนี้"),
                ("today_tomorrow", "รับการประชุมของวันนี้และพรุ่งนี้"),
                ("week", "รับการประชุมของสัปดาห์นี้"),
                ("next_week", "รับการประชุมของสัปดาห์หน้า"),
                ("settings", "เปลี่ยนการตั้งค่าภาษา")
            ]
        }
    }[language]