def get_texts(language):
    return {
        'uk': {
            'greeting': "Привіт! Ласкаво просимо до бота.",
            'choose_language': "Будь ласка, оберіть вашу мову:",
            'language_set': "Мова встановлена на Українську.",
            'available_commands': "Ось доступні команди:",
            'menu_notice': "Ви також можете знайти ці команди в меню.",
            'command_descriptions': [
                ("start", "Почати взаємодію з ботом"),
                ("show_meetings", "Показати зустрічі"),
                ("show_user_meetings", "Показати ваші зустрічі"),
                ("manage_notifications", "Керувати сповіщеннями"),
                ("subscribe_notifications", "Підписатися на сповіщення"),
                ("unsubscribe_notifications", "Відписатися від сповіщень"),
                ("create_meeting", "Створити зустріч")
            ],
            'no_meetings': "Немає зустрічей.",
            'no_user_meetings': "Немає зустрічей для вас.",
            'meeting_title': "Назва зустрічі",
            'meeting_time': "Час зустрічі",
            'meeting_location': "Місце зустрічі",
            'meeting_attendees': "Учасники",
            'no_location': "Місце не вказано",
            'current_notifications': "Поточні налаштування сповіщень",
            'notify_day_before': "Сповіщення за день до",
            'notify_hour_before': "Сповіщення за годину до",
            'notify_five_minutes_before': "Сповіщення за 5 хвилин до",
            'subscribed_notifications': "Ви підписалися на сповіщення.",
            'unsubscribed_notifications': "Ви відписалися від сповіщень.",
            'enter_meeting_title': "Введіть назву зустрічі:",
            'enter_meeting_start_time': "Введіть час початку зустрічі (YYYY-MM-DDTHH:MM:SS):",
            'enter_meeting_end_time': "Введіть час закінчення зустрічі (YYYY-MM-DDTHH:MM:SS):",
            'enter_meeting_location': "Введіть місце зустрічі (необов'язково):",
            'enter_meeting_attendees': "Введіть учасників зустрічі (через кому):",
            'meeting_created': "Зустріч успішно створена.",
            'meeting_creation_failed': "Не вдалося створити зустріч."
        },
        'ru': {
            'greeting': "Здравствуйте! Добро пожаловать в бота.",
            'choose_language': "Пожалуйста, выберите ваш язык:",
            'language_set': "Язык установлен на Русский.",
            'available_commands': "Вот доступные команды:",
            'menu_notice': "Вы также можете найти эти команды в меню.",
            'command_descriptions': [
                ("start", "Начать взаимодействие с ботом"),
                ("show_meetings", "Показать встречи"),
                ("show_user_meetings", "Показать ваши встречи"),
                ("manage_notifications", "Управлять уведомлениями"),
                ("subscribe_notifications", "Подписаться на уведомления"),
                ("unsubscribe_notifications", "Отписаться от уведомлений"),
                ("create_meeting", "Создать встречу")
            ],
            'no_meetings': "Нет встреч.",
            'no_user_meetings': "Нет встреч для вас.",
            'meeting_title': "Название встречи",
            'meeting_time': "Время встречи",
            'meeting_location': "Место встречи",
            'meeting_attendees': "Участники",
            'no_location': "Место не указано",
            'current_notifications': "Текущие настройки уведомлений",
            'notify_day_before': "Уведомление за день до",
            'notify_hour_before': "Уведомление за час до",
            'notify_five_minutes_before': "Уведомление за 5 минут до",
            'subscribed_notifications': "Вы подписались на уведомления.",
            'unsubscribed_notifications': "Вы отписались от уведомлений.",
            'enter_meeting_title': "Введите название встречи:",
            'enter_meeting_start_time': "Введите время начала встречи (YYYY-MM-DDTHH:MM:SS):",
            'enter_meeting_end_time': "Введите время окончания встречи (YYYY-MM-DDTHH:MM:SS):",
            'enter_meeting_location': "Введите место встречи (необязательно):",
            'enter_meeting_attendees': "Введите участников встречи (через запятую):",
            'meeting_created': "Встреча успешно создана.",
            'meeting_creation_failed': "Не удалось создать встречу."
        }
    }[language]
