# -*- coding: utf-8 -*-
STRINGS = {
    "greeting": "Привет! Нажмите на кнопку ниже, чтобы открыть мини-приложение настроек и встреч.",
    "settings_done": "Настройки сохранены.",
    "settings_filter_intro": "Выберите вариант фильтра:",
    "settings_filter_all": "Показывать все встречи",
    "settings_filter_mine": "Показывать только мои встречи",
    "settings_filter_saved": "Настройки фильтра сохранены.",
    "settings_filter_standalone": "Фильтр сохранен.",
    "settings_notifications_intro": "Выберите настройки уведомлений.",
    "settings_notifications_1h": "Уведомлять за 1 час до встречи?",
    "settings_notifications_15m": "Уведомлять за 15 минут до встречи?",
    "settings_notifications_5m": "Уведомлять за 5 минут до встречи?",
    "settings_notifications_new": "Уведомлять о новой встрече?",
    "settings_notifications_saved": "Настройки уведомлений сохранены.",
    "yes_button": "Да",
    "no_button": "Нет",
    "no_meetings": "Нет встреч.",
    "notify_before_meeting": "Напоминание о встрече:\n{details}",
    "notify_new_meeting": "Добавлена новая встреча:\n{details}",
    "meeting_details": "Название: {title}\nУкраина: {start_ua} - {end_ua}\nТаиланд: {start_th} - {end_th}\nУчастники: {attendants}\nМесто: {location}\nСсылка: {link}\nОписание: {desc}",
    "menu_title": "Команды:",
    "menu_start": "/start - Открыть мини-приложение",
    "menu_settings_filter": "/settings_filter - Настройка фильтра",
    "menu_settings_notifications": "/settings_notifications - Настройка уведомлений",
    "menu_get_today": "/get_today - Встречи на сегодня",
    "menu_get_tomorrow": "/get_tomorrow - Встречи на завтра",
    "menu_get_rest_week": "/get_rest_week - Встречи до конца этой недели",
    "menu_get_next_week": "/get_next_week - Встречи на следующей неделе",
    "ukraine_time": "Украина: {start} - {end}",
    "thailand_time": "Таиланд: {start} - {end}",
    "location_label": "Место: {location}",
    "link_label": "Ссылка: {link}",
    "description_label": "Описание: {description}",
    "meetings_for_today": "ВСТРЕЧИ НА СЕГОДНЯ ({date}):",
    "meetings_for_tomorrow": "ВСТРЕЧИ НА ЗАВТРА ({date}):",
    "meetings_for_day_of_week": "ВСТРЕЧИ НА {weekday} ({date}):",
    "weekdays": ["Понедельник","Вторник","Среду","Четверг","Пятницу","Субботу","Воскресенье"]
}
